version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: fitness_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: fitness_db
      MYSQL_USER: fitness_user
      MYSQL_PASSWORD: fitness_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: 